name: Deploy Static Website to Azure

on:
  push:
    branches:
      - main  # Trigger the action when code is pushed to the "main" branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu-based runner for the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from your repository

    - name: Set up Azure CLI
      uses: azure/setup-azure-cli@v1  # Set up Azure CLI for interacting with Azure

    - name: Deploy to Azure Storage
      env:
        AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      run: |
        az storage blob upload-batch \
          -d '$web' \
          -s ./public \
          --account-name webprojectstorage1 \
          --account-key $AZURE_STORAGE_KEY

name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - master  # or your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'Deploy to Azure Static Web Apps'
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        app_location: "/"
        api_location: ""
        output_location: ""
skip_app_build: true 
